// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCVs8v1STFb5G0j7V0eKawywpf5jTmaNgA',
    appId: '1:837795914268:web:64301ff4aedce69fb435d9',
    messagingSenderId: '837795914268',
    projectId: 'escortservice-d2f11',
    authDomain: 'escortservice-d2f11.firebaseapp.com',
    storageBucket: 'escortservice-d2f11.firebasestorage.app',
    measurementId: 'G-QH3J8003J3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC7uNTzzFhcBaRf-cmuCe5BEgk0uZ--aZY',
    appId: '1:837795914268:android:c808cfc5c5eac9a8b435d9',
    messagingSenderId: '837795914268',
    projectId: 'escortservice-d2f11',
    storageBucket: 'escortservice-d2f11.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD0up0egmW3c8Uq7S73VYfhyO12wf_N2kg',
    appId: '1:837795914268:ios:575672ccda497e63b435d9',
    messagingSenderId: '837795914268',
    projectId: 'escortservice-d2f11',
    storageBucket: 'escortservice-d2f11.firebasestorage.app',
    iosBundleId: 'com.example.escort',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD0up0egmW3c8Uq7S73VYfhyO12wf_N2kg',
    appId: '1:837795914268:ios:575672ccda497e63b435d9',
    messagingSenderId: '837795914268',
    projectId: 'escortservice-d2f11',
    storageBucket: 'escortservice-d2f11.firebasestorage.app',
    iosBundleId: 'com.example.escort',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCVs8v1STFb5G0j7V0eKawywpf5jTmaNgA',
    appId: '1:837795914268:web:511c1e87e35709beb435d9',
    messagingSenderId: '837795914268',
    projectId: 'escortservice-d2f11',
    authDomain: 'escortservice-d2f11.firebaseapp.com',
    storageBucket: 'escortservice-d2f11.firebasestorage.app',
    measurementId: 'G-KWV8E6MNN7',
  );
}
