name: Deploy to Firebase Hosting on merge

on:
  push:
    branches:
      - main  # Monitor the main branch for changes

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest  # Use the latest Ubuntu environment for this job

    steps:
      # Step 1: Checkout the code
      - name: Checkout code
        uses: actions/checkout@v4

      # Step 2: Set up Flutter environment
      - name: Set up Flutter 3.5.4
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.5.4'  # Use Flutter version 3.5.4

      # Step 3: Deploy to Firebase Hosting
      - name: Deploy to Firebase Hosting
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: ${{ secrets.GITHUB_TOKEN }}  # GitHub token for authorization
          firebaseServiceAccount: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_ESCORTSERVICE_D2F11 }}  # Firebase service account secret
          channelId: live  # Deploy to live channel
          projectId: escortservice-d2f11  # Firebase project ID
